In [1]:
import numpy as np

In [16]:
a=np.zeros(int(input('enter size of array:')))

enter size of array:3


In [18]:
for i in range(a.size):
    a[i]=float(input('enter {} no:'.format(i+1)))

enter 1 no:10
enter 2 no:20
enter 3 no:30


In [20]:
a

array([10., 20., 30.])

In [21]:
a=a+2

In [22]:
a

array([12., 22., 32.])

In [23]:
a=a+a*(10/100)

In [24]:
a

array([13.2, 24.2, 35.2])

In [35]:
b=np.array([2,3,4])

In [36]:
b

array([2, 3, 4])

In [37]:
c=a+b

In [38]:
c

array([15.2, 27.2, 39.2])

In [39]:
np.max(c)

39.2

In [40]:
np.max(a)

35.2

In [41]:
np.max(b)

4

In [42]:
a.max()

35.2

In [43]:
np.argmax(c)

2

In [44]:
np.argmin(c)

0

In [45]:
a=np.array([20,21,19,23,22,21,25,26,25,24,21,20,18,19,29,28])

In [46]:
np.unique(a)

array([18, 19, 20, 21, 22, 23, 24, 25, 26, 28, 29])

In [47]:
np.unique(a).size

11

In [49]:
np.bincount(a)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 3,
       1, 1, 1, 2, 1, 0, 1, 1], dtype=int64)

In [51]:
aa=np.bincount(a)

In [52]:
aa[18:]

array([1, 2, 2, 3, 1, 1, 1, 2, 1, 0, 1, 1], dtype=int64)

In [72]:
a=np.array([1,2,3,4,-5])

In [73]:
np.absolute(a)

array([1, 2, 3, 4, 5])

In [74]:
a

array([ 1,  2,  3,  4, -5])

In [79]:
np.sort(a,kind='mergesort')

array([-5,  1,  2,  3,  4])

In [80]:
a=np.array([20,21,19,23,22,21,25,26,25,24,21,20,18,19,29,28])

In [81]:
np.mean(a)

22.5625

In [82]:
np.median(a)

21.5

In [90]:
np.unique(a)[np.bincount(a).max()]

21

In [91]:
a

array([20, 21, 19, 23, 22, 21, 25, 26, 25, 24, 21, 20, 18, 19, 29, 28])

In [92]:
a[a%2==0]

array([20, 22, 26, 24, 20, 18, 28])

In [100]:
a=np.array([[1,2,3,4],[1,4,5,6],[2,7,8,9]])

In [101]:
a.ndim

2

In [102]:
a

array([[1, 2, 3, 4],
       [1, 4, 5, 6],
       [2, 7, 8, 9]])

In [103]:
print(a)

[[1 2 3 4]
 [1 4 5 6]
 [2 7 8 9]]


In [104]:
a.shape

(3, 4)

In [105]:
a.shape[1]

4

In [106]:
a.size

12

In [107]:
type(a)

numpy.ndarray

In [111]:
a.flatten()

array([1, 2, 3, 4, 1, 4, 5, 6, 2, 7, 8, 9])

In [109]:
a

array([[1, 2, 3, 4],
       [1, 4, 5, 6],
       [2, 7, 8, 9]])

In [112]:
a.reshape(4,3)

array([[1, 2, 3],
       [4, 1, 4],
       [5, 6, 2],
       [7, 8, 9]])

In [113]:
a

array([[1, 2, 3, 4],
       [1, 4, 5, 6],
       [2, 7, 8, 9]])

In [114]:
a.resize(4,3)

In [115]:
a

array([[1, 2, 3],
       [4, 1, 4],
       [5, 6, 2],
       [7, 8, 9]])

In [116]:
a=np.zeros([2,3])

In [117]:
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [118]:
a=np.ones([3,3])

In [119]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [120]:
a=np.full([3,4],5)

In [121]:
a

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [123]:
a=np.eye(3,3)

In [124]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [125]:
b=np.array([[1,2,3],[3,2,1],[2,4,6]])

In [126]:
b

array([[1, 2, 3],
       [3, 2, 1],
       [2, 4, 6]])

In [127]:
c=a+b

In [128]:
c

array([[2., 2., 3.],
       [3., 3., 1.],
       [2., 4., 7.]])

In [129]:
c=c*5

In [130]:
c

array([[10., 10., 15.],
       [15., 15.,  5.],
       [10., 20., 35.]])

In [131]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [132]:
b

array([[1, 2, 3],
       [3, 2, 1],
       [2, 4, 6]])

In [134]:
np.hstack([a,b])

array([[1., 0., 0., 1., 2., 3.],
       [0., 1., 0., 3., 2., 1.],
       [0., 0., 1., 2., 4., 6.]])

In [135]:
np.vstack([a,b])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 2., 3.],
       [3., 2., 1.],
       [2., 4., 6.]])

In [136]:
d=np.array([[1,2,3],[2,3,4]])

In [137]:
d

array([[1, 2, 3],
       [2, 3, 4]])

In [138]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [139]:
np.vstack([a,d])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 2., 3.],
       [2., 3., 4.]])