In [1]:
import numpy as np

In [2]:
list=[1,2,3,.5,.6,1.6]

In [3]:
a=np.array(list)

In [7]:
np.bincount(list)

array([2, 2, 1, 1], dtype=int64)

In [8]:
a1=np.array([10,20,30])

In [9]:
a2=np.array([8,20,30])

In [10]:
np.where(a1==a2)

(array([1, 2], dtype=int64),)

In [11]:
np.where(a1!=a2)

(array([0], dtype=int64),)

In [14]:
a=np.arange(1,10)

In [15]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
a.resize(3,3)

In [17]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
a[1,0]

4

In [19]:
a[-1,1]

8

In [20]:
a[0:2:1,0:3:1]

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
a[0:2:,0:3:]

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
a[0:2,0:3]

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
a[:2,:3]

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
a[:2,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
a[::2,:]

array([[1, 2, 3],
       [7, 8, 9]])

In [28]:
a[-1::-2,1:]

array([[8, 9],
       [2, 3]])

In [29]:
a[-1:-3:-1,-1::-2]

array([[9, 7],
       [6, 4]])

In [30]:
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]],[[2,4],[3,4]]])

In [31]:
a.ndim

3

In [32]:
a.size

12

In [33]:
a.shape

(3, 2, 2)

In [34]:
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]],

       [[2, 4],
        [3, 4]]])

In [35]:
a[0]

array([[1, 2],
       [3, 4]])

In [36]:
a=np.arange(12)

In [37]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [38]:
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
a.reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [41]:
b=a.reshape(3,2,2)

In [42]:
b

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [43]:
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])