In [1]:
import numpy as np

In [2]:
np.__version__

'1.14.0'

In [3]:
a=np.array([1,2,3])

In [4]:
type(a)

numpy.ndarray

In [9]:
a=np.array([1,2,3.5])

In [10]:
a

array([1. , 2. , 3.5])

In [14]:
a=np.array([1,2,3.5],dtype=np.int8)

In [12]:
a

array([1, 2, 3], dtype=int8)

In [15]:
a=np.array([1,2,130],dtype=np.int8)

In [16]:
a

array([   1,    2, -126], dtype=int8)

In [17]:
a=np.arange(1,5,1)

In [18]:
a

array([1, 2, 3, 4])

In [19]:
a=np.arange(1,2,.1)

In [20]:
a

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [21]:
a=np.zeros(5)

In [22]:
a

array([0., 0., 0., 0., 0.])

In [23]:
a=np.ones(5)

In [24]:
a

array([1., 1., 1., 1., 1.])

In [30]:
a=np.full(5,10)

In [31]:
a

array([10, 10, 10, 10, 10])

In [32]:
b=a

In [33]:
b

array([10, 10, 10, 10, 10])

In [34]:
b[0]=100

In [35]:
b

array([100,  10,  10,  10,  10])

In [36]:
a

array([100,  10,  10,  10,  10])

In [37]:
c=np.copy(a)

In [38]:
c

array([100,  10,  10,  10,  10])

In [39]:
a[0]=500

In [40]:
a

array([500,  10,  10,  10,  10])

In [41]:
c

array([100,  10,  10,  10,  10])

In [42]:
a=np.linspace(1,10,5)

In [43]:
a

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [44]:
a=np.linspace(1,10)

In [45]:
a

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [48]:
a=np.random.random(5)

In [49]:
a

array([0.07062789, 0.207325  , 0.16166775, 0.55480937, 0.05267597])

In [50]:
a=np.random.uniform(1,10,5)

In [51]:
a

array([8.92477641, 1.90781894, 7.24243009, 6.13748544, 7.51595861])

In [54]:
a=np.random.randint(1,100,5)

In [55]:
a

array([56, 43, 55, 91, 96])

In [56]:
a[0]=10

In [57]:
a

array([10, 43, 55, 91, 96])

In [58]:
a.size

5

In [59]:
a.ndim

1

In [60]:
type(a)

numpy.ndarray

In [61]:
a.dtype

dtype('int32')

In [64]:
a1=np.insert(a,1,100)

In [65]:
a

array([10, 43, 55, 91, 96])

In [66]:
a1

array([ 10, 100,  43,  55,  91,  96])

In [67]:
id(a)

2194135973936

In [68]:
id(a1)

2194135975216

In [69]:
a2=np.append(a,500)

In [70]:
a2

array([ 10,  43,  55,  91,  96, 500])

In [71]:
a3=np.delete(a,0)

In [72]:
a3

array([43, 55, 91, 96])

In [73]:
a[0]

10

In [74]:
a[0:2]

array([10, 43])