It is actually a problem of classification.
* logistic says first solve the problem with linear regression

In [1]:
import pandas as pd
from sklearn.linear_model import LinearRegression
import numpy as np

In [2]:
df=pd.read_csv('dataset/insurance.csv',sep='\t')

In [3]:
df

Age  Have_Insurance
0    22               0
1    25               0
2    47               1
3    52               0
4    46               1
5    56               1
6    55               0
7    60               1
8    62               1
9    61               1
10   18               0
11   28               0
12   27               0
13   29               0
14   49               1

In [4]:
X= df.iloc[:,:-1].values
y= df.iloc[:,-1].values

In [5]:
Lrg=LinearRegression()

In [6]:
Lrg.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [7]:
pred=Lrg.predict(X)

In [8]:
pred #predicted value of y using the Linear Regression

array([-0.02413319,  0.04780816,  0.57537804,  0.69528028,  0.55139759,
        0.79120208,  0.76722163,  0.88712387,  0.93508477,  0.91110432,
       -0.12005499,  0.1197495 ,  0.09576905,  0.14372995,  0.62333893])

In [9]:
new_y=[]
for i in pred:
    new_y.append(1/(1+np.exp(-i)))



In [10]:
new_y

[0.4939669951108734,
 0.5119497631372888,
 0.6400032004428511,
 0.6671405203540283,
 0.6344597809754411,
 0.6880893815903716,
 0.6829195699059479,
 0.7082962846315415,
 0.7181057358164714,
 0.7132260881464,
 0.47002225087354654,
 0.5299016521006897,
 0.5239239811050551,
 0.5358707570108879,
 0.6509775555522485]

In [11]:
from sklearn.linear_model import LogisticRegression

In [13]:
lr=LogisticRegression()

In [14]:
lr.fit(X,y)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [15]:
lr.predict_proba(X)

array([[0.62265161, 0.37734839],
       [0.5975478 , 0.4024522 ],
       [0.40640403, 0.59359597],
       [0.36475498, 0.63524502],
       [0.41491965, 0.58508035],
       [0.33280358, 0.66719642],
       [0.34066206, 0.65933794],
       [0.30231902, 0.69768098],
       [0.28768529, 0.71231471],
       [0.29494937, 0.70505063],
       [0.65510723, 0.34489277],
       [0.5719221 , 0.4280779 ],
       [0.58051415, 0.41948585],
       [0.56328646, 0.43671354],
       [0.38954513, 0.61045487]])

In [16]:
lr.predict(X)

array([0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1], dtype=int64)