Traditional Programming Vs Machine Learning prog.
---------------------------------------------------------------------------

TP:
---
* In this type of programming we use a static formula or multiple conditions to perform a task. For eg- calculating factorial, division in result, even/odd, simple interest.
* Accuracy is 100%.
*   Input
      |  
    Program
      |
    Output

ML:
---
* It is a technique to develop such programs that do not contain a fixed formula to solve a problem.
*  Data        Input
       \      /
       Programs
   (Dynamically build logic)
           |
        Output
        
 * data here has input and output both
 
 
 Types of ML:
 ------------------
 1. Supervised Learning- Input and Output is given already.
 2. UnSupervised Learning- Output isn't present in the given data.
 3. Reinforceent Learning- No data for the past. Data predicted would be input for the second time.
 4. Semi supervised- Output of some data is given but for some data it is not given.
 
- Inputs in ML are known as Features/Dimensions.
- Output is known as Target/class/Label.
- Row in the dataset having Input and Output is known as Instance/Observation/Vector/Sample.
- Feature Vector- Vector without the output.


Steps Involved in Machine Learning:
---------------------------------------------------
->Collecting the data
->Data preprocessing
->training the model
->Predicting results by Inputs from user
->Accuracy of the result
->Evaluation
 
 - target is not always catogorized(class based) values could be continuous too.
 *    Supervised  Learning
          /          \
   classification  Regression    
 
 * Libraries of machine learning - scikit learn(2006-2007), tensorflow(2015-2016)(developed by google)
 * sklearn Algos- KNN 
                - Linear Regression
                - Logistic Regression
                - Decision Tree
                - Random Forest
                - SVM
                - Naive Bayes' classifier
                
                


In [1]:
import pandas as pd

In [2]:
df= pd.read_csv('dataset/fruits.csv')

In [3]:
df.head()

diameter  weight FruitName
0       6.0     100     Apple
1       6.1      95     Apple
2       3.0      30    Banana
3       3.2      35    Banana
4       5.5      80     Apple

# K Nearest Neighbor 

In [5]:
from sklearn.neighbors import KNeighborsClassifier

In [6]:
knn= KNeighborsClassifier() #model or classifier or estimator

In [7]:
knn.fit(df.iloc[:,:-1].values,df.iloc[:,-1].values)     #fit is used to train the model

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [8]:
knn.predict([[5.3,68]])

array(['Apple'], dtype=object)

In [9]:
knn.predict([[2.3,28]])

array(['Banana'], dtype=object)

In [48]:
import pandas as pd

In [49]:
df=pd.read_csv("dataset/online_ads.csv")

In [50]:
df.head()

Gender  Age  EstimatedSalary  Purchased
0    Male   19            19000          0
1    Male   35            20000          0
2  Female   26            43000          0
3  Female   27            57000          0
4    Male   19            76000          0

In [51]:
df.isnull().sum()

Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [52]:
from sklearn.neighbors import KNeighborsClassifier

In [53]:
knn= KNeighborsClassifier()

In [54]:
df['Gender']=df.Gender.map({'Male':1,'Female':2})   #for categorical variable.. we do encoding
X=df.iloc[:,:-1].values   #features
y=df.iloc[:,-1].values    #target
#df.head()

In [15]:
y.ndim

1

In [16]:
type(X)

numpy.ndarray

In [55]:
knn.fit(X,y)  #displays error because one feature(gender is categorical)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [56]:
knn.predict([[1,25,20000],[2,25,20000]])  #no purchase

array([0, 0], dtype=int64)

In [57]:
knn.predict([[1,25,40000],[1,47,25000]])

array([0, 0], dtype=int64)

In [58]:
knn.predict(X)

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1,

In [59]:
pred= knn.predict(X)

In [60]:
from sklearn.metrics import accuracy_score

In [61]:
accuracy_score(y,pred)

0.8725

Model evaluation:
------------------------
done by two methods- 
1. training data
2. testing data

In [62]:
df.shape

(400, 4)

In [65]:
X_train=df.iloc[:300,:-1].values
y_train= df.iloc[:300,-1].values
X_test=df.iloc[300:,:-1].values
y_test=df.iloc[300:,-1].values

In [66]:
knn= KNeighborsClassifier()

In [67]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=5, p=2,
           weights='uniform')

In [68]:
y1=knn.predict(X_train)
y2=knn.predict(X_test)

In [69]:
accuracy_score(y_train,y1)

0.8966666666666666

In [70]:
accuracy_score(y_test,y2)

0.61

In [71]:
from sklearn.model_selection import train_test_split

In [72]:
X_train, X_test, y_train, y_test=train_test_split(X,y, test_size= 0.2)

In [76]:
X_test.shape

(80, 3)

In [97]:
knn=KNeighborsClassifier(n_neighbors=9)
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=9, p=2,
           weights='uniform')

In [98]:
y1=knn.predict(X_train)

In [99]:
y2=knn.predict(X_test)

In [100]:
accuracy_score(y_train,y1)

0.8625

In [101]:
accuracy_score(y_test,y2)

0.7375