In [1]:
import cv2
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('haarcascade_eye.xml')

cap= cv2.VideoCapture(0)
while True:
    ret, img= cap.read()
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, 1.3, 5)
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
        roi_gray = gray[y:y+h, x:x+w]
        print(roi_gray)
        roi_color= img[y:y+h, x:x+w]
        eyes = eye_cascade.detectMultiScale(roi_gray)
        for (ex, ey, ew, eh) in eyes:
            cv2.rectangle(roi_color, (ex,ey), (ex+ew,ey+eh), (0,255,0))
    cv2.imshow('img', img)
    k= cv2.waitKey(30) & 0xFF
    if k==27 :
        break
cap.release()
cv2.destroyAllWindows()
    

[[18 17 17 ... 16 15 16]
 [17 18 16 ... 16 16 16]
 [16 17 16 ... 15 16 16]
 ...
 [47 46 45 ... 15 13 12]
 [45 44 44 ... 14 13 12]
 [46 45 45 ... 14 14 12]]
[[ 59  59  55 ...  36  36  34]
 [ 56  58  55 ...  38  35  35]
 [ 59  57  53 ...  39  35  36]
 ...
 [101 102 101 ...  18  20  22]
 [103 103 102 ...  17  19  23]
 [101 103 105 ...  16  18  23]]
[[ 79  83  80 ...  45  50  53]
 [ 81  81  79 ...  46  52  54]
 [ 78  80  82 ...  53  58  55]
 ...
 [123 124 125 ...  23  21  21]
 [122 124 124 ...  27  24  20]
 [122 122 123 ...  25  26  26]]
[[102 102 103 ...  64  64  63]
 [100  99 103 ...  65  69  71]
 [107 101 103 ...  69  73  74]
 ...
 [146 146 144 ...  33  32  49]
 [155 155 145 ...  38  39  44]
 [154 153 145 ...  35  44  49]]
[[ 99 102  99 ...  66  69  70]
 [ 99 100  99 ...  67  70  71]
 [105 102 100 ...  73  69  71]
 ...
 [150 147 148 ...  25  25  28]
 [148 147 153 ...  19  23  26]
 [146 150 149 ...  22  22  27]]
[[126 120 119 ...  96  92  90]
 [124 125 122 ...  95  89  92]
 [123 125 127 

In [4]:
import cv2
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier('haarcascade_eye.xml')

img=cv2.imread('radhika.jpg')

gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
faces = face_cascade.detectMultiScale(gray, 1.3, 5)
for (x,y,w,h) in faces:
    cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
    roi_gray = gray[y:y+h, x:x+w]
    roi_color= img[y:y+h, x:x+w]
    eyes = eye_cascade.detectMultiScale(roi_gray)
    for (ex, ey, ew, eh) in eyes:
        cv2.rectangle(roi_color, (ex,ey), (ex+ew,ey+eh), (0,255,0))
    cv2.imshow('img', img)
    k= cv2.waitKey(30) & 0xFF
    if k==27 :
        break
        
        
img.release()
cv2.destroyAllWindows()

AttributeError: 'numpy.ndarray' object has no attribute 'release'